### ISSUE TITLE
Meta data form needs css as additonal field

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#15]
- [x] We need for the settings form to add a Page style  ( Style de la page)fields that will use the upload media component

<img width="1198" alt="Screenshot 2023-07-20 at 15 30 49" src="https://github.com/Geeks-Solutions/nuxt-sections/assets/82215775/71eb510f-3da2-45bd-bba4-f0a22a83fa84">

- [x] When clicking on the upload media component it will open the mini BO and show only the documents folder 
- [x] When choosing the css media and saving the settings, the url of the css file will be added in the metadata of the page

**Acceptance testing**

- [x] Have the css file field added in the settings form with the upload media component
- [x] Clicking on the css file field should open the Mini BO with only documents only 
- [x] When choosing the css file and saving the setting it must be added to the metadata of the page

**Comment by akramsarkis** [comment]
@mahfouzhseineweev  I have one comment, if I reached my limit , the error message is not displayed correctly even though I am indeed redirected to the upgrade package page

<img width="1304" alt="Screenshot 2023-07-31 at 10 17 29" src="https://github.com/Geeks-Solutions/nuxt-sections/assets/82215775/6e76c2fc-f66c-4091-b64e-a3cb836cba6f">
<img width="738" alt="Screenshot 2023-07-31 at 10 20 21" src="https://github.com/Geeks-Solutions/nuxt-sections/assets/82215775/1f1c8ed8-01e0-4c07-86f9-0869f01df26c">

**Comment by akramsarkis** [comment]
all good now
